print(not True)
print(not False)
print(not 7)

print(True or False)
print(True and False)
print(2 or 3 or 4)
print(False or 0 or 4 or True)
print(1 and 2 and 3)
print (1 and 0.0 and 4)
print(False or 0 or None)